# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "12200301960bbde64052db068cf31a64091ce1f671898513d9b8d9e2be5b0e4b13a3";
    path = fetchzip {
      url = "https://github.com/zigzap/facil.io/archive/refs/tags/zap-0.0.12.tar.gz";
      hash = "sha256-dSlMecImqHjU9lenNsVSHdfMZWYHyIdNd3cuUCMY/rI=";
    };
  }
  {
    name = "122067d12bc7abb93f7ce623f61b94cadfdb180cef12da6559d092e6b374202acda3";
    path = fetchzip {
      url = "https://github.com/zigzap/zap/archive/refs/tags/v0.1.14-pre.tar.gz";
      hash = "sha256-4OvpFKqtDgd/zzGft9Sa/SyWC/tECpfR3Sqt6sTOXqQ=";
    };
  }
]
